name: hello-ricardofiallos
version: '0.1'
summary: GNU hello, the "hello world" snap
description: GNU hello a friendly greeting
grade: stable
confinement: strict

apps:
	hello:
		command: bin/hello

	parts:
		gnu-hello:
			source: http://ftp.gnu.org/gnu/hello/hello-2.10.tar.gz
				plugin: autotools
